- name: Install all softwares
  hosts: dev
  become: yes
  gather_facts: false 
  vars_files:
  - vars.yml


  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'virtualenv',
       'pip', 'python3-dev', 'mysql-server', 'mysql-client', 'python3-pymysql', 'default-libmysqlclient-dev', 'build-essential', 'default-jdk', 'default-jre']

   
    - name: Remove directory if exists
      shell: sudo rm -rf /home/ubuntu/*

    - name: Add Scripts directory
      command: mkdir /home/ubuntu/scripts

    - name: Transfer executable script mysql
      copy: src=../aula_inicial/scripts/mysql.sh dest=/home/ubuntu/scripts/mysql.sh mode=0777  


    - name: download jenkins
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present


    - name: ensure the Repository is configured
      apt_repository: repo='deb http://pkg.jenkins.io/debian-stable binary/' state=present

    - name: update apt cache
      apt:
        update_cache: yes
        state: latest

    - name: install jenkins
      apt:
        name: jenkins
        state: latest

    - name: Start Jenkins
      service:
        name: jenkins
        enabled: true
        state: started

    - name: copy .my.cnf file with root password credentials
      template: src=../configs/mysqld.cnf  dest=/etc/mysql/mysql.conf.d/mysqld.cnf owner=root mode=0600

    - name: update mysql root password for all root accounts
      mysql_user:
        name: root
        host: localhost
        password: "{{ new_mysql_root_password }}"


    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    # Creates the number of containers defined by the variable create_containers, using values from vars file
    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: present
      with_sequence: count={{ create_containers }}

    

    - name: Open Jenkins port
      ufw:
        state: enabled
        rule: allow
        port: "8080"
        proto: tcp

    - name: Open SSH port
      ufw:
        state: enabled
        rule: allow
        port: "22"
        proto: tcp

    - name: Open SSH port
      ufw:
        state: enabled
        rule: allow
        port: "3306"
        proto: tcp



    

    


